#import "../../../templates/typst/chapter.typ": technical-chapter, abstract, academic-table, chapter-bibliography

#show: technical-chapter.with(
  title: [On-Policy Alignment and #linebreak()Iterative Policy Improvement],
)

#abstract[
  On-policy alignment improves a language-model policy using responses generated by a recent version of that same policy. The apparent simplicity of this idea hides an important systems and statistical contract: every selected response must be traceable to the behavior policy, generation configuration, reward or verifier version, and filtering decision that produced it. This chapter develops the rollout lifecycle, policy-version semantics, exploration and selection, rejection-style policy filtering, and Expert Iteration as an iterative improvement pattern. It then treats DAPO as a concrete modern design, explaining its dynamic sampling, asymmetric clipping, token-level objective, and overlong-response shaping. The emphasis is on how online data, relative rewards, and policy updates form a moving training distribution rather than a static preference dataset.
]

= Introduction <sec-on-policy-introduction>

Chapters 15--18 introduced a progression from preference data to Reward Models, PPO, DPO, and GRPO. The distinction between offline preference learning and online policy optimization is now central. An offline method can train on a fixed collection of comparisons. An on-policy method instead asks a recent language-model policy to generate candidate responses, scores those responses, and uses them to update the policy that will generate the next collection. The data distribution therefore changes as training proceeds.

This feedback loop is especially useful when a verifier can score newly sampled solutions, as in the reasoning settings of Chapter 19. It is also delicate. A response may be excellent under one policy version but be treated incorrectly after the learner has moved far away from that behavior policy. A filter that improves average reward may remove the very difficult cases required for robust generalization. A rollout worker can produce many candidates, but no amount of throughput repairs an ambiguous reward contract. This chapter focuses on these algorithmic interfaces. The distributed worker topology used to execute them is deferred to Chapter 22.

= On-Policy Data and Policy Versions <sec-on-policy-data-and-versions>

Let $pi_(theta_v)$ denote the behavior policy at version $v$, and let $pi_theta$ denote the policy currently being optimized. For a prompt $x ~ cal(D)$, a rollout $y = (y_1, dots, y_T)$ is sampled autoregressively from the behavior policy,

$
  y ~ pi_(theta_v)(. | x)
  = product_(t = 1)^T pi_(theta_v)(y_t | x, y_<t).
$ <eq-on-policy-behavior-policy>

The word *on-policy* means that optimization uses data from the policy being improved, or from a deliberately bounded recent behavior version. By contrast, *off-policy* data comes from a behavior distribution that is not guaranteed to be recent for the update; a fixed preference dataset is a particularly important offline source. A stale rollout is therefore not a separate objective: it is a behavior-policy sample whose version is becoming too distant for the declared on-policy approximation. Practical systems may tolerate limited lag, but they must not silently relabel arbitrary historical data as fresh Rollouts.

This does not mean that a production learner and generator must share one instantaneous set of parameters. In practice, an update may reuse one rollout batch for several optimization epochs, or a generator may finish requests while a learner begins a later update. The essential requirement is that this lag is recorded and controlled.

A useful rollout record contains more than text:

$
  r = (x, y, v, ell_"old", m, R, h),
$ <eq-on-policy-rollout-record>

where $ell_"old"$ is the behavior-policy token log-probability, $m$ is the response-token mask, $R$ is the reward or verifier result, and $h$ identifies the generation, reward, and selection configurations. The record makes an update auditable. In particular, a PPO- or GRPO-style importance ratio compares a candidate policy to the actual behavior policy,

$
  rho_t(theta; v)
  = frac(
    pi_theta(y_t | x, y_<t),
    pi_(theta_v)(y_t | x, y_<t),
  ).
$ <eq-on-policy-ratio>

When $theta$ drifts far from $theta_v$, this ratio becomes more variable and a nominally on-policy update becomes a weak approximation. Policy versions, log-probabilities, response masks, and a maximum allowed lag are therefore training data, not incidental logging.

== The Rollout Lifecycle <sec-on-policy-rollout-lifecycle>

An online alignment iteration has a compact but consequential lifecycle:

#align(center)[
  *Roll out* $arrow$ *score* $arrow$ *select* $arrow$ *update* $arrow$ *refresh version*
]

The prompt distribution may be fixed, sampled from a curriculum, or refreshed from a task pool. The generation configuration---temperature, maximum response length, stop conditions, and any format constraint---changes which trajectories are observed, so it belongs in $h$ in @eq-on-policy-rollout-record. Scoring can be a learned Reward Model, a deterministic checker, a process signal, or a combination, but its version must be equally explicit. Finally, the selected records are transformed into token-level learning signals and used for a bounded number of updates before another rollout round begins.

Exploration is not merely random noise. Sampling temperature, multiple Rollouts per prompt, prompt diversity, and task difficulty determine whether the learner observes useful alternatives. Very low diversity repeatedly trains on one familiar solution pattern; unconstrained diversity can spend most computation on malformed or unscorable trajectories. Chapter 19 explains why multiple candidates can increase both learning signal and inference-time success probability. Here the additional point is that sampling policy and selection policy jointly define the next training distribution.

= Selection, Filtering, and Iterative Improvement <sec-on-policy-selection-and-iteration>

When rewards are sparse or evaluation is expensive, systems often retain only a subset of sampled responses. Let $w(x, y)$ be a nonnegative selection weight; binary policy filtering uses $w in {0, 1}$. The distribution after filtering is, schematically,

$
  p_"selected"(y | x)
  = frac(
    pi_(theta_v)(y | x) w(x, y),
    sum_(y') pi_(theta_v)(y' | x) w(x, y'),
  ).
$ <eq-on-policy-selection-distribution>

This expression exposes a trade-off. Rejection-style selection can remove invalid outputs, failed verifier checks, duplicate answers, or obviously low-quality candidates. It can also bias the retained data toward short, easy, stylistically preferred, or already-solved cases. It is therefore not the distribution-preserving accept--reject correction used in exact speculative sampling (Chapter 27). It is a deliberate change to the data distribution and must be evaluated as such.

*Verifier-guided selection* is particularly attractive when correctness is executable. A mathematics checker, unit-test suite, or symbolic validator can identify candidates that satisfy a declared condition without claiming to judge every dimension of response quality. A learned score can rank candidates where no deterministic verifier exists, but it imports the calibration, style bias, and reward-hacking risks discussed in Chapters 15 and 20. A filter should retain its reason code and score, not only its final accept/reject bit.

== Expert Iteration and Self-Improvement <sec-on-policy-expert-iteration>

*Expert Iteration* is a general pattern in which a current policy produces or helps search for solutions, a stronger selection procedure identifies better behavior, and the policy is trained to imitate or optimize toward that selected behavior. In the original formulation, planning provides the stronger expert signal while a neural policy generalizes it @anthony2017expert. In language-model reasoning, the selector may instead be a verifier, a search procedure, or a reward rule:

$
  pi_(theta_v)
  arrow "sample or search"
  arrow "select verified candidates"
  arrow "update"
  pi_(theta_(v+1)).
$ <eq-on-policy-expert-iteration>

The loop is not guaranteed to improve itself. If the selector favors a superficial format, the next policy can become better at that format rather than at the task. If generated data lacks unsolved cases, the learner receives little new corrective information. ReST is one example of alternating generation and reward-filtered improvement for language models; it illustrates both the practical appeal of selected self-generated data and the need to state the filter and update regime precisely @gulcehre2023rest.

= DAPO: A Concrete On-Policy Design <sec-on-policy-dapo>

DAPO (Decoupled Clip and Dynamic sAmpling Policy Optimization) is an open implementation-oriented design for large-scale LLM reasoning reinforcement learning. Its reported formulation builds on group-relative Rollouts, but changes several details that become important for long reasoning responses: dynamic sampling, a decoupled clipping range, a token-level policy-gradient loss, and overlong-response shaping @yu2025dapo. These choices are useful to study because they make otherwise implicit decisions about which Rollouts enter an update and how individual tokens are weighted.

For a prompt $q$ with answer $a$, sample a group $(o_i)_(i=1)^G$ from an old policy. In the binary-verification setting of the original formulation, define

$
  c(q) = sum_(i = 1)^G 1["equivalent"(a, o_i)].
$ <eq-dapo-correct-count>

Groups with $c(q) = 0$ or $c(q) = G$ have no within-group correctness variation and give zero standardized relative advantage. Dynamic sampling oversamples prompts and retains groups satisfying $0 < c(q) < G$, then refills the batch as necessary. This can concentrate rollout compute on prompts that currently provide a contrastive learning signal. It must not be interpreted as a universal rule: it can underrepresent consistently solved, consistently unsolved, or non-binary-reward tasks.

== Ratios, Asymmetric Clipping, and Group Advantages <sec-on-policy-dapo-clipping>

For each response token, DAPO uses the behavior-policy ratio

$
  r_(i,t)(theta)
  = frac(
    pi_theta(o_(i,t) | q, o_(i,<t)),
    pi_(theta_"old")(o_(i,t) | q, o_(i,<t)),
  ).
$ <eq-dapo-token-ratio>

With group rewards $R_i$, let $mu_R = frac(1, G) sum_j R_j$ and $s_R = sqrt(frac(1, G) sum_j (R_j - mu_R)^2)$. A representative relative advantage is

$
  hat(A)_i
  = frac(R_i - mu_R, s_R + epsilon).
$ <eq-dapo-relative-advantage>

The exact reward and normalization conventions are implementation contracts. In the published binary-reward setting, the same response-level relative advantage is applied to its valid tokens. The clipped local objective is

$
  ell_(i,t)(theta)
  = min(
    r_(i,t)(theta) hat(A)_i,
    "clip"(r_(i,t)(theta), 1-epsilon_"low", 1+epsilon_"high") hat(A)_i,
  ).
$ <eq-dapo-clipped-token-objective>

PPO commonly presents a symmetric interval around one. DAPO separates the bounds and, in its Clip-Higher design, uses an upper allowance that can be larger than the lower one. Increasing $epsilon_"high"$ permits a larger probability increase for advantageous tokens; keeping $epsilon_"low"$ relatively small limits large probability decreases. This is a design for maintaining useful exploration, not a proof that asymmetric clipping is always preferable. The ratio and clipping behavior should be monitored alongside KL drift and entropy even when an implementation does not include the same explicit KL term used by classical RLHF in Chapter 16.

== Token-Level Loss and Long Responses <sec-on-policy-dapo-token-level>

Let $N_"tok" = sum_(i = 1)^G |o_i|$ count valid response tokens in a group. A token-level group objective can be written as

$
  J_"DAPO"(theta)
  = op("E")[
    frac(1, N_"tok")
    sum_(i = 1)^G sum_(t = 1)^(|o_i|) ell_(i,t)(theta)
  ].
$ <eq-dapo-token-level-objective>

This differs from first normalizing each response by its own length and then averaging responses equally. Under @eq-dapo-token-level-objective, a longer response contributes more valid token terms. That can give a correct long reasoning trace more influence, but it also makes response-length behavior part of the optimization objective. Token masks must exclude prompt, padding, and post-termination positions; otherwise the apparent change in weighting is an indexing bug rather than an algorithmic choice.

The original DAPO system also uses a shaped length penalty near a maximum rollout length. With a maximum $L_"max"$ and a soft interval $L_"cache"$, one representative form is

$
  R_"length"(y) = cases(
    0 & |y| <= L_"max" - L_"cache", \\
    frac(L_"max" - L_"cache" - |y|, L_"cache")
      & L_"max" - L_"cache" < |y| <= L_"max", \\
    -1 & |y| > L_"max".
  )
$ <eq-dapo-overlong-reward>

The soft region avoids treating every near-limit response identically, while the terminal penalty discourages trajectories that exhaust the length budget. Its purpose is not to make all answers short. A length penalty must be checked against task correctness, because some problems genuinely require a longer derivation.

= Data Quality, Modes, and Monitoring <sec-on-policy-quality-and-monitoring>

Online data quality is conditional on the current policy. A batch with high mean reward can still be low value if it contains duplicates, template exploitation, nearly identical easy prompts, or reward artifacts. Conversely, a low reward batch can be informative if it contains calibrated hard cases and enough variation to form a stable relative signal. Curriculum, prompt-source mixture, sampling configuration, verifier coverage, and selection thresholds should therefore be versioned with every update.

#figure(
  block(width: 100%)[
    #set text(size: 8.75pt)
    #set par(justify: false, leading: 0.53em, spacing: 0pt)
    #academic-table(
      columns: (1.28fr, 1.38fr, 1.76fr),
      align: (left, left, left),
      inset: (x: 3.8pt, y: 2.45pt),
      header: (
        [*Signal*], [*What it can reveal*], [*Required interpretation*],
      ),
      rows: (
        [Policy lag and ratios], [Stale behavior data or overly large updates.], [Read with update epochs, clip fraction, and policy-version spread.],
        [Group reward variance], [Whether relative advantages are informative.], [Separate all-success and all-failure groups from noisy rewards.],
        [Selection rate], [Filter strictness and rollout-compute waste.], [Stratify by prompt source, length, and difficulty.],
        [Response length and stop rate], [Overlong behavior, truncation, or shortcut responses.], [Check jointly with correctness and length shaping.],
        [Entropy, KL, and clip fraction], [Exploration loss or excessive policy movement.], [Compare against behavior and reference-policy contracts.],
        [Held-out task and regression scores], [Whether online reward gains transfer.], [Use the multi-objective suite of Chapter 20.],
      ),
    )
  ],
  caption: [Online alignment metrics must be interpreted jointly. No single rollout statistic establishes durable policy improvement.],
) <tab-on-policy-monitoring>

The principal failure modes are coupled. Overly strict filtering can cause mode collapse; weak filtering can train on invalid outputs. A stale rollout pool can invalidate an assumed on-policy update; excessively fresh but narrow data can overfit one policy mode. A verifier can be objective about a narrow property yet still be exploitable through answer formatting or loopholes. The remedy is not a larger reward number, but a reproducible decomposition: inspect prompt distribution, generation configuration, selection decision, reward or verifier trace, advantage statistics, update size, and held-out behavior in that order.

= Implementation Contracts <sec-on-policy-implementation-contracts>

An implementation should treat on-policy alignment as a versioned data pipeline. Each rollout must record its behavior-policy version, token log-probabilities, response mask, prompt identifier, generation configuration, reward or verifier version, and selection reason. The learner must enforce a bounded policy lag and reject or explicitly reweight records outside that contract. Prompt, completion, padding, and terminal tokens need unambiguous masks; only intended completion tokens receive policy-gradient loss.

Group construction must specify group size, reward normalization, zero-variance handling, and whether all-success or all-failure groups are retained. Filters should preserve enough metadata to audit selection bias by source, difficulty, length, language, and reward mode. Length limits, shaped penalties, stop conditions, and answer parsing must be evaluated with correctness rather than optimized as isolated proxy metrics. Finally, online metrics need held-out, human, or deterministic regression evidence as specified in Chapter 20.

= Summary <sec-on-policy-summary>

On-policy alignment replaces a static training corpus with a moving distribution produced by a recent policy. That change creates a powerful route to verifier-guided learning and iterative policy improvement, but it makes provenance, policy versioning, exploration, selection, and distribution shift first-class algorithmic concerns. Rejection-style filtering and Expert Iteration can turn sampled candidates into stronger supervision only when their selectors are reliable and their biases are measured. DAPO makes four practical choices explicit: retain informative mixed-outcome groups, separate clipping bounds, weight valid tokens directly, and shape overlong responses. These are levers in a coupled online system, not independent recipes. The next systems chapter will address how Rollout, reward, policy, and critic work is organized and scheduled at distributed scale.

#pagebreak(weak: true)

#heading(level: 1, numbering: none, outlined: false)[References]
#chapter-bibliography("/references/handbook.bib")
